language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
before_script:
- chmod +x ./utils/update-gh-pages.sh
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - ./utils/update-gh-pages.sh
env:
  global:
  - GH_REF: github.com/voischev/bem-social.git
  - secure: GR67HlGjAXHyy6HGYJHwX8CIG6G0wHr+gQtO2sK+5raK0deJN+0wXACiXiIQ+x5bTHBfnKHAsZmt0yr7s4gvKU0D3D3zwUXzJlSCFtVFrL7mKjRzZM/uKJ4lqpCUqpyx3nzc7ohELh5F3iCJgcygJ72yrzoVWCouksEipGVIRUg=
  - secure: J6L6ZO6WVvzSFL0Iiw2xSkY3LSlJ1K/85Op0fEUZaKuhXmws1eGdG7nfl2KODIyA4fCMWzu04tJym7bovu3jpmQCjsMlKH96eXauUo6Zf1+ozKNnkwVQ9qCyqvsrBZbQM4Vv9sXqBP0YlzCUQBHEifp5U7cKSVBElp60Q9GVgnI=
# matrix:
#   include:
#     - TEST_SCOPE: lint
